### ISSUE TITLE
Hi. Great Talk on Performance, Question about vuex and modules

### ISSUE THREAD

**Issue by ricky11** [kb-coder/lazydemo#2]
Hi.  

I have lazy loaded all my chunks in the router, but i still find they are loaded when i click the network tab "ALL"..  However when i go to "xhr" i do see the routes loaded when i navigate to that route..   It was confusing at first, but i found out that most browsers will just prefetch the content anyway and will increase the download time and hurt performance even though we have already specified to lazy load the routes.   The solution to this is in vue config to :   config.plugins.delete('prefetch').

However my next problem is how do i disable vuex from loading on the home page if my home page is not using any global state?   Im Why load the store if its not being used on the index route.

also, in vuex, i have lots of third party packages (already trimmed most of them) but some of them like aws-sdk are quite large, and this seems to get loaded everywhere even when not being used.  
How do i lazy load modules within modules? most of these are located in vuex store.

I wish vue did have a good way to deal with this.

thanks
Rishi

**Comment by kb-coder** [comment]
@ricky11 Yes, you do have to add the `config.pluigins.delete('prefetch')`. Good job there.

Vuex is global, so I don't think there is a way around loading it globally. One technique I use in my router is to load the initial state or look up values for that module in a beforeRouteEnter. If it is a heavy process to load the initial state, then you may not want to do that because the user experience may not be good.

For the vendors chunk, you can try different regex combinations and do like what I did on the Vue section in the vue.config:
```
config.optimization.set('splitChunks', {
        cacheGroups: {
          // aws modules
          aws: {
            test: /[\\/]node_modules[\\/](aws.*)[\\/]/, // this is not exact, but change this to be whatever matching works.
            name: 'aws',
            enforce: true,
            priority: 20,
            chunks: 'initial',
          },
```

You'll want to be sure to exclude this new package from vendors:
```
vendors: {
            name: 'chunk-vendors',
            test(module) {
              // `module.resource` contains the absolute path of the file on disk.
              // Note the usage of `path.sep` instead of / or \, for cross-platform compatibility.
              return module.resource
              && !module.resource.includes(`${path.sep}node_modules${path.sep}@vue`)
              && !module.resource.includes(`${path.sep}node_modules${path.sep}vue`)
              && !module.resource.includes(`${path.sep}node_modules${path.sep}aws`) // added this
              && !module.resource.includes(`${path.sep}src${path.sep}`);
            },
```

Hope that helps!
